### PR TITLE
dracut/30ignition/module-setup.sh: include groupmod binary in initramfs

### LINKED ISSUE #2186: groupmod executable is not found during ignition phase
# Bug #

The changes introduced in #2158 results in ignition failing when it tries to handle an existing group. Not sure if this is an ignition issue or openSUSE MicroOS issue.

## Operating System Version ##

openSUSE MicroOS

## Ignition Version ##

Ignition 25.1

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?

It is running on x64 bare metal.

## Expected Behavior ##

Group handling behavior should be idempotent. Ignition should not fail if a group already exists on the system.

## Actual Behavior ##

Ignition fails with 

```
files: ensureGroups: op(1): [started] modifying group GROUP_NAME
files: ensureGroups: op(1): executing: "groupmod" "--root" "/sysroot" GROUP_NAME
files failed 
files: ensureGroups: op(1): [failed] modifying group GROUP_NAME: exec "groupmod": executable file not found in $PATH: Cmd: "groupmod" "--root" "/sysroot" GROUP_NAME Stdout: "" Stderr: ""
```

## Reproduction Steps ##

  1. Install OpenSUSE MicroOS and configure with ignition.
  2. Remove /etc/machine-id to trigger ignition in the next boot.
  3. Reboot the machine.

### PR DESCRIPTION
**Pull request by onurhanak**
Resolves #2186 . Adds groupmod binary to initramfs for the changes made in pull request [#2158](https://github.com/coreos/ignition/pull/2158) to work.

### CODE REVIEW

**Comment by prestist** [comment]
@onurhanak  thank you for working on this! sorry I had been busy on other tasks and this slipped my radar. I will take a look tomorrow.

**Comment by onurhanak** [comment]
Hi @prestist , is there any progress on this? Is there anything I can do to speed things up?

File: dracut/30ignition/module-setup.sh [hunk 1]
```diff
@@ -14,9 +14,12 @@ depends() {
 }
 
 install_ignition_unit() {
-    local unit="$1"; shift
-    local target="${1:-ignition-complete.target}"; shift
-    local instantiated="${1:-$unit}"; shift
+    local unit="$1"
```
Comment (prestist) [inline dracut/30ignition/module-setup.sh:17]: Hmm, between this formatting change and the spacing below I think we can keep the formatting the same or make it an intentional commit, so that functional and stylistic choices are separated.

File: dracut/30ignition/module-setup.sh [hunk 2]
```diff
@@ -110,23 +114,22 @@ install() {
 }
 
 installkernel() {
-     # required by hyperv platform to read kvp from the kernel
-     instmods hv_utils
+    # required by hyperv platform to read kvp from the kernel
+    instmods hv_utils
 
-     # required by applehv platform to read ignition file through vsock
-     instmods -c vsock
```
Comment (prestist) [inline dracut/30ignition/module-setup.sh:117]: Hmm, between this formatting change and the "shift" changes above, I think we can keep the formatting the same or make it an intentional commit along so that functional and stylistic choices are separated.

File: docs/release-notes.md [hunk 3]
```diff
@@ -14,6 +14,8 @@ nav_order: 9
 
 ### Bug fixes
 
+- Include `groupmod` binary in initramfs ([#2190](https://github.com/coreos/ignition/pull/2190))
```
Comment (prestist) [inline docs/release-notes.md:17]: This can be committed with the functional change so they are bound.

**Comment by onurhanak** [comment]
@prestist Thanks, I edited my PR.
