### PR TITLE
filesystemEntries: create hard links to files that are deeper than the hard link

### LINKED ISSUE #800: Ignition cannot create hard links to files it creates deeper than the link
# Bug #

## Ignition Version ##
v2.0.0+

## Expected Behavior ##

Ignition can create hard links to files  (or symlinks) that are also specified in a config that are as deep or deeper than the hard link.

## Actual Behavior ##
Ignition will fail since the hard link is created before the target

## Reproduction Steps ##
```
{
  "ignition": { "version": "3.0.0" },
  "storage": {
    "files": [{
      "path": "/foo/bar/baz"
    }],
    "links": [{
      "path": "/foo/quux",
      "target": "/foo/bar/baz",
      "hard": true
    }]
  }
}
```

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Fixes #800 
/cc @arithx

### CODE REVIEW

**Comment by bgilbert** [comment]
ok to test

File: internal/exec/stages/files/filesystemEntries.go [hunk 1]
```diff
@@ -236,10 +237,21 @@ func (s stage) getOrderedCreationList(config types.Config) ([]filesystemEntry, e
...
+			hardlinks = append(hardlinks, linkEntry(l))
+		}
+
 	}
 	sort.Slice(entries, func(i, j int) bool { return util.Depth(entries[i].node().Path) < util.Depth(entries[j].node().Path) })
 
+	// Append all the hard links to the list after the sort function.
+	// For more information: https://github.com/coreos/ignition/issues/800
+	for _, hardlink := range hardlinks {
+		entries = append(entries, hardlink)
```
Comment (arithx) [inline internal/exec/stages/files/filesystemEntries.go:253]: Rather than looping you can append it like so `entries = append(entries, hardlinks...)`

File: tests/positive/files/link.go [hunk 2]
```diff
@@ -360,7 +360,6 @@ func ForceHardLinkCreation() types.Test {
 		ConfigMinVersion: configMinVersion,
 	}
 }
-
```
Comment (arithx) [inline tests/positive/files/link.go:363]: Don't think this line removal was intentional.

File: tests/positive/files/link.go [hunk 3]
```diff
@@ -360,6 +361,58 @@ func ForceHardLinkCreation() types.Test {
 		ConfigMinVersion: configMinVersion,
 	}
 }
+
+// HardLinkCreation checks if the ignition can create
+// a hard link to a file that's deeper than the hard link.
```
Comment (arithx) [inline tests/positive/files/link.go:366]: Would be nice to link to the specific issue.

File: tests/positive/files/link.go (hunk 2 above)
Comment (sohankunkerkar) [reply tests/positive/files/link.go:363]: Fixed

File: internal/exec/stages/files/filesystemEntries.go [hunk 4]
```diff
@@ -224,7 +224,7 @@ func (s stage) getOrderedCreationList(config types.Config) ([]filesystemEntry, e
 		f.Path = path
 		entries = append(entries, fileEntry(f))
 	}
-
```
Comment (bgilbert) [inline internal/exec/stages/files/filesystemEntries.go:227]: Dropped space.

File: internal/exec/stages/files/filesystemEntries.go [hunk 5]
```diff
@@ -236,10 +236,20 @@ func (s stage) getOrderedCreationList(config types.Config) ([]filesystemEntry, e
...
+		if l.Hard != nil && *l.Hard {
+			hardlinks = append(hardlinks, linkEntry(l))
+		} else {
+			entries = append(entries, linkEntry(l))
+		}
+
 	}
 	sort.Slice(entries, func(i, j int) bool { return util.Depth(entries[i].node().Path) < util.Depth(entries[j].node().Path) })
 
+	// Append all the hard links to the list after the sort function that will
```
Comment (bgilbert) [inline internal/exec/stages/files/filesystemEntries.go:248]: `...after sorting.  This allows...`

File: tests/positive/files/link.go [hunk 6]
```diff
@@ -360,6 +361,59 @@ func ForceHardLinkCreation() types.Test {
 		ConfigMinVersion: configMinVersion,
 	}
 }
+
+// CreateDeepHardLinkToFile checks if Ignition can create a hard
+// link to a file that's deeper than the hard link.
+// For more information: https://github.com/coreos/ignition/issues/800
+func CreateDeepHardLinkToFile() types.Test {
+	name := "links.hard.create.file"
```
Comment (bgilbert) [inline tests/positive/files/link.go:369]: `deep` should probably be somewhere in this name too.

File: tests/positive/files/link.go (hunk 2 above)
Comment (dustymabe) [reply tests/positive/files/link.go:363]: I only see a single blank line in between the two functions. @bgilbert - maybe refresh?

File: tests/positive/files/link.go [hunk 7]
```diff
@@ -361,6 +362,58 @@ func ForceHardLinkCreation() types.Test {
...
+	configMinVersion := "3.0.0"
+
+	return types.Test{
+		Name:             name,
+		In:               in,
+		Out:              out,
+		Config:           config,
+		ConfigMinVersion: configMinVersion,
+	}
+}
```
Comment (dustymabe) [inline tests/positive/files/link.go:416]: need to add extra blank line after this function?

File: tests/positive/files/link.go (hunk 2 above)
Comment (bgilbert) [reply tests/positive/files/link.go:363]: It was removed in the first commit and re-added in the second.

Comment (dustymabe) [reply tests/positive/files/link.go:363]: ahh, yes I see that if I look at the first commit by itself.

Comment (sohankunkerkar) [reply tests/positive/files/link.go:363]: Fixed
